import type { Metadata } from "next";
import "../styles/globals.css";
import StoreProvider from "@/lib/store/store-provider";
import SessionProvider from "@/providers/auth-provider";
import { getServerSession } from "next-auth";
import { Slide, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { TranslationProvider } from "@/Context/TranslationContext";

export const strokeWidthdata: Metadata = {
  title: "Findly",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body>
        <StoreProvider>
        <TranslationProvider>
          <SessionProvider session={session}>{children} </SessionProvider></TranslationProvider>
          <ToastContainer
            autoClose={1000}
            position="bottom-right"
            hideProgressBar={true}
            closeOnClick
            pauseOnHover
            draggable
            theme="colored"
            newestOnTop
            transition={Slide}
            toastStyle={{
              width: "auto",
              maxWidth: "90%",
              padding: "10px 20px",
              wordBreak: "break-word",
            }}
          />
        </StoreProvider>
      </body>
    </html>
  );
}
